# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml
### https://www.appveyor.com/docs/build-configuration/

# Build version format
version: appveyor-build-{build}

# Test against this version of Node.js
environment:
  NODE_ENV: test

  matrix:
    - nodejs_version: "6"
    # - nodejs_version: "stable"
    # - nodejs_version: "5.4.1"

build: off

services:
  - mongodb

branches:
  only:
    - master

install:
  # ps: prefix means to run this command in PowerShell
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm config set progress=false
  - npm install --force

# # scripts that are called at very beginning, before repo cloning
# init:
#   # Fix line endings on Windows
#   - git config --global core.autocrlf true

# to run your custom scripts instead of automatic tests
test_script:
  # Output useful info for debugging.
  - node --version && npm --version
  # We test multiple Windows shells because of prior stdout buffering issues
  - ps: "npm --version # PowerShell" # Pass comment to PS for easier debugging
  - cmd: npm run test

cache:
#  - node_modules
