sudo: required
dist: trusty
addons:
  chrome: stable
  # apt:
  #   sources:
  #     - google-chrome
  #   packages:
  #     - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

language: node_js
node_js:
  - "6"
# env:
#   - TEST_DIR=.
#   - TEST_DIR=mobile/fcc1apps
# script: cd $TEST_DIR && npm install && npm test
# before_install:
#   - npm i -g npm@5

branches:
  only:
  - master
git:
  depth: 5
cache:
  directories:
  - node_modules

services:
  - mongodb
#  - redis-server

after_success:
  - npm run coveralls
