#!/usr/bin/env bash

# file: curl.sh
# /*!
#  * Copyright 2017 ikarus512
#  * https://github.com/ikarus512/tripSave.git
#  *
#  * DESCRIPTION: curl for development server
#  * AUTHOR: ikarus512
#  * CREATED: 2017/08/11
#  *
#  * MODIFICATION HISTORY
#  *  2017/08/11, ikarus512. Initial version.
#  *
#  * USAGE EXAMPLE
#  *  devcurl -X GET --data {} https://ikarus512-fcc1.herokuapp.com/app1/api/polls
#  *
#  */

args=$(echo "$*" | perl -e '$_=<>; s/ikarus512-fcc1.herokuapp.com/127.0.0.1:5000/g; print;')
# --insecure
# curl -i $args --silent --cacert ./_certificate/certificate.pem | perl -e 'while(<>){ print; }'
# curl -i $args --silent --cacert ./_certificate/certificate.pem | perl -e '@_=<>; print "$_[0]$_[$#_]";'
curl -i $args --silent --cacert ./_certificate/certificate.pem | perl -e '@_=<>; print "$_[0]$_[$#_]";'
# curl $args | ./node_modules/.bin/jq2 "$"
